<feat-Required> " Added Separate Sorting Algorithm Section "
SayuruRehan/HackFest23 pull request #4
Opened 2023-10-08 05:18 UTC by manikanta-manii

@SayuruRehan 
@Bopitiya77 
@DebarjunChakraborty 
" can you please review and merge with hacktoberfest labels "

2023-10-08 05:59 UTC, SayuruRehan requested changes

2023-10-08 05:59 UTC, SayuruRehan commented on Algorithms/Sorting Algorithms/MergeSort
@manikanta-manii this is not a java file. Pls correct this and commit again

2023-10-08 06:21 UTC, manikanta-manii commented on Algorithms/Sorting Algorithms/MergeSort
okay

2023-10-08 06:27 UTC, manikanta-manii commented on Algorithms/Sorting Algorithms/MergeSort
@SayuruRehan Review please , i have done the Changes !

2023-10-10 02:50 UTC, SayuruRehan approved these changes

2023-10-10 02:54 UTC, merged